export interface SubService {
  slug: string
  category: string
  parentTitle: string
  title: string
  heroHeading?: string
  metaDescription?: string
  desc: string
  featuresIntro?: string
  features: string[]
  result?: string
  stats: { value: string; label: string }[]
  process?: { title: string; desc: string }[]
  faqs?: { q: string; a: string }[]
}

const allSubServices: SubService[] = [
  {
    slug: 'technical-seo', category: 'seo', parentTitle: 'SEO Services', title: 'Technical SEO',
    desc: 'Most SEO campaigns fail because the technical foundation is broken. We fix crawl issues, indexation gaps, rendering problems, and Core Web Vitals before a single piece of content gets written.',
    features: [
      'Full crawl audit using Screaming Frog, Sitebulb, and log file analysis',
      'Core Web Vitals optimization (LCP, INP, CLS) with real-user data',
      'JavaScript rendering audit for SPAs and frameworks',
      'Crawl budget optimization for large sites (50k+ pages)',
      'XML sitemap architecture and robots.txt configuration',
      'Canonicalization, hreflang, and duplicate content resolution',
      'Structured data implementation (FAQ, HowTo, Product, LocalBusiness)',
      'Site speed optimization including image formats, lazy loading, and CDN config',
    ],
    result: 'Average 40% improvement in crawl efficiency within 60 days.',
    stats: [
      { value: '40%', label: 'Avg. crawl efficiency gain' },
      { value: '200+', label: 'Technical checks per audit' },
      { value: '60', label: 'Days to measurable improvement' },
      { value: '94%', label: 'Client retention' },
    ],
    process: [
      { title: 'Crawl & diagnose', desc: 'We run a full technical crawl, analyze server logs, and benchmark Core Web Vitals against your competitors.' },
      { title: 'Prioritize fixes', desc: 'Every issue gets a severity score. We fix high-impact items first so you see results before the full audit is done.' },
      { title: 'Implement & test', desc: 'We ship fixes directly or work with your dev team. Every change is tested in staging before production.' },
      { title: 'Monitor & maintain', desc: 'Ongoing crawl monitoring catches regressions before they impact rankings. Monthly technical health reports.' },
    ],
    faqs: [
      { q: 'What is technical SEO?', a: 'Technical SEO covers the infrastructure of your website — crawlability, indexation, speed, security, and structured data. It ensures search engines can find, understand, and rank your content.' },
      { q: 'How often should a technical audit be done?', a: 'We recommend a full audit quarterly for active sites, and continuous monitoring in between. Sites undergoing development or migration need more frequent checks.' },
      { q: 'Do you work with our developers?', a: 'Yes. We provide developer-ready tickets with exact specifications, priority levels, and expected SEO impact for each fix.' },
    ],
  },
  {
    slug: 'local-seo', category: 'seo', parentTitle: 'SEO Services', title: 'Local SEO',
    desc: 'For businesses that serve specific geographic areas, local SEO is the highest-ROI channel available. We build multi-location SEO systems that scale from 1 storefront to 200+ locations.',
    features: [
      'Google Business Profile optimization and ongoing management',
      'Local citation building and NAP consistency audit',
      'Review generation strategy and reputation monitoring',
      'Local link building from chambers, directories, and community sites',
      'Geo-targeted landing pages with LocalBusiness schema',
      'Google Maps ranking optimization and category strategy',
      'Competitor proximity analysis and market gap identification',
      'Multi-location dashboard with per-location KPI tracking',
    ],
    result: 'Average 3-pack visibility increase of 280% within 90 days.',
    stats: [
      { value: '280%', label: 'Avg. 3-pack visibility increase' },
      { value: '90', label: 'Days to measurable results' },
      { value: '200+', label: 'Local campaigns managed' },
      { value: '4.9', label: 'Avg. client review score' },
    ],
    process: [
      { title: 'Audit local presence', desc: 'We audit your Google Business Profile, citations, reviews, and local link profile against the top 3-pack competitors in your market.' },
      { title: 'Optimize listings', desc: 'GBP optimization, NAP consistency fixes, category strategy, and review generation workflows go live.' },
      { title: 'Build local authority', desc: 'Local link building, geo-targeted landing pages, and community partnerships that search engines trust.' },
      { title: 'Track & scale', desc: 'Per-location KPI dashboards. Monthly reporting. Playbook ready to replicate across new locations.' },
    ],
    faqs: [
      { q: 'How long does local SEO take?', a: 'Most businesses see measurable 3-pack improvements within 60-90 days. Citation building and review velocity are the fastest levers.' },
      { q: 'Do you manage Google Business Profiles?', a: 'Yes. We handle everything: posts, Q&A, review responses, photo optimization, category strategy, and service area configuration.' },
      { q: 'Can you handle multiple locations?', a: 'Yes. We have managed local SEO for businesses with 200+ locations. Our systems scale without diluting any single listing.' },
    ],
  },
  {
    slug: 'ecommerce-seo', category: 'seo', parentTitle: 'SEO Services', title: 'E-commerce SEO',
    desc: 'E-commerce SEO is a different discipline. Faceted navigation, product schema, category architecture, and inventory-driven indexation require specialized knowledge that most generalist agencies lack.',
    features: [
      'Product and category page optimization at scale',
      'Faceted navigation management (filters, sorts, pagination)',
      'Product schema markup (price, availability, reviews, brand)',
      'Programmatic content for long-tail product queries',
      'Internal linking architecture for category authority',
      'Inventory-aware indexation (noindex out-of-stock handling)',
      'Shopify, WooCommerce, Magento, and BigCommerce optimization',
      'Shopping feed optimization for Google Merchant Center',
    ],
    result: 'Average 67% increase in organic revenue within 6 months.',
    stats: [
      { value: '67%', label: 'Avg. organic revenue increase' },
      { value: '6', label: 'Months to significant ROI' },
      { value: '150+', label: 'E-commerce clients served' },
      { value: '8.5x', label: 'Avg. return on retainer' },
    ],
    process: [
      { title: 'Platform audit', desc: 'Full crawl of your store: product pages, faceted nav, category structure, schema, and shopping feeds.' },
      { title: 'Architecture fixes', desc: 'We restructure your category tree, fix canonicals, and implement inventory-aware indexation rules.' },
      { title: 'Content at scale', desc: 'Programmatic category descriptions, product enrichment, and long-tail content that captures purchase-intent queries.' },
      { title: 'Revenue tracking', desc: 'Organic revenue attribution dashboards. You see exactly which SEO work drove which sales.' },
    ],
    faqs: [
      { q: 'Which platforms do you work with?', a: 'Shopify, WooCommerce, Magento, BigCommerce, and custom-built stores. Platform-specific optimization is included in every engagement.' },
      { q: 'How do you handle out-of-stock products?', a: 'We implement inventory-aware indexation rules that prevent out-of-stock pages from wasting crawl budget while preserving link equity for when products return.' },
      { q: 'Do you optimize product feeds?', a: 'Yes. Google Merchant Center feed optimization is included. We improve titles, descriptions, categories, and custom labels for Shopping performance.' },
    ],
  },
  {
    slug: 'enterprise-seo', category: 'seo', parentTitle: 'SEO Services', title: 'Enterprise SEO',
    desc: 'Enterprise sites have enterprise problems: thousands of stakeholders, legacy CMSs, dev queues measured in quarters. We know how to navigate the politics and ship the work.',
    features: [
      'Cross-functional SEO roadmapping with dev, product, and content teams',
      'Large-scale migration planning and execution (domain, CMS, redesign)',
      'International SEO with hreflang, subdomain, and ccTLD strategy',
      'Programmatic page generation for thousands of location or product pages',
      'Executive reporting with revenue attribution and board-ready dashboards',
      'SEO governance frameworks and publishing workflows',
      'Competitor intelligence monitoring at the portfolio level',
      'Integration with enterprise tools (Conductor, BrightEdge, seoClarity)',
    ],
    result: 'Managed migrations for 12 enterprise clients with zero traffic loss.',
    stats: [
      { value: '12', label: 'Enterprise migrations with zero traffic loss' },
      { value: '50k+', label: 'Pages managed per client' },
      { value: '0', label: 'Traffic loss on migrations' },
      { value: '94%', label: 'Client retention rate' },
    ],
    process: [
      { title: 'Stakeholder mapping', desc: 'We identify every team that touches SEO: dev, product, content, legal. Then we build a governance framework that gets work shipped.' },
      { title: 'Technical remediation', desc: 'Migration planning, international architecture, and large-scale crawl optimization handled by our most senior engineers.' },
      { title: 'Programmatic scale', desc: 'Thousands of location, product, or service pages generated from structured data with unique, optimized content.' },
      { title: 'Executive reporting', desc: 'Board-ready dashboards with revenue attribution. Monthly strategy calls with your C-suite.' },
    ],
    faqs: [
      { q: 'How do you handle enterprise dev queues?', a: 'We write implementation specs that your developers can ship independently. We also integrate with Jira, Asana, and Monday to track SEO tickets inside your existing workflow.' },
      { q: 'Do you handle site migrations?', a: 'Yes. We have managed 12 enterprise migrations with zero traffic loss. Migration planning is one of our core specializations.' },
      { q: 'How do you handle international SEO and multilingual indexation?', a: 'We architect robust hreflang clustering, ccTLD and subdirectory structures, geo-targeted sitemaps, and localized content canonicals to prevent cross-language keyword cannibalization across multinational domains.' },
    ],
  },
  {
    slug: 'seo-audits', category: 'seo', parentTitle: 'SEO Services', title: 'SEO Audits',
    desc: 'A standalone, one-time deliverable. Our forensic SEO audit is a 60-90 page document covering every dimension of your search presence. No retainer required.',
    features: [
      '200+ point technical audit with severity scoring',
      'Content gap analysis against your top 10 SERP competitors',
      'Backlink profile audit with toxic link identification',
      'Keyword opportunity mapping with difficulty and volume data',
      'Core Web Vitals assessment with specific remediation steps',
      'Information architecture review and internal linking analysis',
      'AI search readiness score (ChatGPT, Gemini, Perplexity visibility)',
      '90-minute strategy call to walk through findings and priorities',
    ],
    result: 'Delivered 400+ audits. 78% of audit clients convert to retainers.',
    stats: [
      { value: '400+', label: 'Audits delivered' },
      { value: '78%', label: 'Audit-to-retainer conversion' },
      { value: '200+', label: 'Checks per audit' },
      { value: '90', label: 'Minute strategy call included' },
    ],
    process: [
      { title: 'Access & crawl', desc: 'We get access to your analytics, Search Console, and server. Then we run a full technical crawl and competitor analysis.' },
      { title: 'Deep analysis', desc: 'Two weeks of forensic analysis across technical health, content gaps, backlink profile, and AI search readiness.' },
      { title: 'Report delivery', desc: 'A 60-90 page document with every finding scored by severity and prioritized by impact.' },
      { title: 'Strategy call', desc: '90-minute walkthrough with a senior strategist. Plain English, prioritized next steps, and a clear execution roadmap.' },
    ],
    faqs: [
      { q: 'Do I need a retainer to get an audit?', a: 'No. The audit is a standalone deliverable. Walk away with a roadmap your team can execute independently.' },
      { q: 'How long does the audit take?', a: 'From access to delivery: approximately three weeks. The strategy call is scheduled within one week of report delivery.' },
      { q: 'What tools and crawlers do you use during the forensic audit?', a: 'We employ enterprise crawl engines including Screaming Frog and Sitebulb alongside server log analysis, Ahrefs, Semrush, Google Search Console API exports, and Google Lighthouse/CrUX field data.' },
    ],
  },
  {
    slug: 'chatgpt', category: 'ai-search', parentTitle: 'AI Search & GEO', title: 'ChatGPT Optimization',
    desc: 'ChatGPT Search processes millions of queries daily. When someone asks "best SEO agency for e-commerce," does your brand appear? We engineer the conditions that make ChatGPT cite you consistently.',
    features: [
      'ChatGPT brand mention audit across 50+ industry-specific prompts',
      'Entity optimization on Wikipedia, Wikidata, and Crunchbase',
      'Content restructuring for answer extraction by LLMs',
      'Third-party mention generation through digital PR',
      'Competitor displacement strategy for high-value queries',
      'Monthly citation tracking with sentiment analysis',
    ],
    result: 'Avg. 340% increase in ChatGPT brand mentions within 120 days.',
    stats: [
      { value: '340%', label: 'Avg. increase in brand mentions' },
      { value: '120', label: 'Days to measurable results' },
      { value: '50+', label: 'Prompts tested per audit' },
      { value: '93%', label: 'Positive citation sentiment' },
    ],
    process: [
      { title: 'Citation audit', desc: 'We query ChatGPT with 50+ prompts relevant to your industry and document every mention, competitor, and gap.' },
      { title: 'Entity building', desc: 'Wikipedia, Wikidata, Crunchbase, and third-party mention campaigns to establish your brand as a recognized entity.' },
      { title: 'Content engineering', desc: 'Restructure your content for LLM extraction: answer-first formatting, structured data, and authority signals.' },
      { title: 'Monthly tracking', desc: 'Automated prompt testing with citation frequency, accuracy, sentiment, and competitive share of voice reports.' },
    ],
    faqs: [
      { q: 'Can you guarantee ChatGPT mentions?', a: 'No honest agency can. What we guarantee is a systematic, proven approach. Our clients see an average 340% increase within 120 days.' },
      { q: 'How do you track AI mentions?', a: 'We run automated prompt testing weekly across ChatGPT, tracking citation frequency, accuracy, and sentiment over time.' },
      { q: 'What structural changes make web content easily cited by ChatGPT?', a: 'We implement direct answer-first paragraph structuring, clear tabular data comparisons, schema entity disambiguation, and authoritative statistical citations that LLM retrieval-augmented generation (RAG) models prioritize.' },
    ],
  },
  {
    slug: 'google-aio', category: 'ai-search', parentTitle: 'AI Search & GEO', title: 'Google AI Overviews',
    desc: 'Google AI Overviews now appear on 40%+ of informational queries. They pull from indexed web pages, but the selection criteria differ from traditional rankings. We optimize specifically for AIO inclusion.',
    features: [
      'AI Overview trigger query identification for your industry',
      'Content formatting for AIO extraction (lists, tables, definitions)',
      'Structured data enhancement for AI-parseable content',
      'Source authority building through E-E-A-T signals',
      'Competitor AIO displacement analysis',
      'Weekly AIO appearance tracking and reporting',
    ],
    result: 'Clients average 12 new AI Overview citations per month.',
    stats: [
      { value: '12', label: 'New AIO citations per month (avg)' },
      { value: '40%', label: 'Of queries now show AI Overviews' },
      { value: '6x', label: 'Higher CTR from AIO citations' },
      { value: '85%', label: 'Client AIO visibility increase' },
    ],
    faqs: [
      { q: 'How do Google AI Overviews differ from traditional featured snippets?', a: 'Featured snippets pull a single block of text from one top-ranking URL. AI Overviews synthesize multi-source information using Gemini LLM models, prioritizing pages with clear semantic entities, structured data, and high E-E-A-T credentials.' },
      { q: 'Does appearing in an AI Overview reduce click-through rates?', a: 'While simple factual queries may result in zero-click answers, commercial and investigative queries in AI Overviews display prominent carousel citation cards that generate substantially higher qualified buyer intent and lower bounce rates.' },
      { q: 'How quickly can our pages be indexed into Google AI Overviews?', a: 'Once content is re-structured with modular summary blocks, structured tables, and clean semantic schema, Google re-evaluates the query cluster within 2 to 4 weeks depending on site authority and crawl frequency.' },
    ],
  },
  {
    slug: 'gemini', category: 'ai-search', parentTitle: 'AI Search & GEO', title: 'Gemini Optimization',
    desc: 'Gemini powers Google Search AI, Android assistants, and enterprise tools. We ensure your brand is recognized as an entity across the entire Gemini ecosystem.',
    features: [
      'Google Knowledge Panel creation and optimization',
      'Gemini-specific entity recognition testing',
      'Schema markup alignment with Google AI parsing',
      'Brand authority building through Google Merchant and Business Profile',
      'Cross-platform visibility testing (Search, Workspace, Android)',
      'Quarterly Gemini readiness assessments',
    ],
    result: 'Average Knowledge Panel activation rate of 85% within 90 days.',
    stats: [
      { value: '85%', label: 'Knowledge Panel activation rate' },
      { value: '90', label: 'Days to panel activation' },
      { value: '3', label: 'Platforms covered (Search, Workspace, Android)' },
      { value: '100%', label: 'Entity audit coverage' },
    ],
    faqs: [
      { q: 'How does Gemini Optimization affect visibility across Google products?', a: 'Gemini powers Google Search AI, Android assistants, and Google Workspace integrations. Optimizing for Gemini strengthens your Google Knowledge Graph entity, ensuring accurate brand representation across all Google surface areas.' },
      { q: 'What role does Google Knowledge Panel claim and verification play?', a: 'Knowledge Panels provide the factual ground truth that Gemini references. We establish authoritative Wikidata entries, disambiguate parent organization hierarchies, and secure verified entity panels for your leadership and company.' },
      { q: 'How do you track Gemini recommendations and brand sentiment?', a: 'We run scheduled prompt testing across Gemini Advanced querying high-intent buyer searches in your vertical, logging brand mention frequency, recommended alternatives, and factual accuracy.' },
    ],
  },
  {
    slug: 'perplexity', category: 'ai-search', parentTitle: 'AI Search & GEO', title: 'Perplexity SEO',
    desc: 'Perplexity always cites sources. This makes it the highest-value AI search platform for brands that can produce authoritative content. We optimize your content library to be Perplexity\'s preferred source.',
    features: [
      'Source authority audit for Perplexity citation eligibility',
      'Content depth optimization for complex query handling',
      'Data-first content creation (original research, surveys, reports)',
      'Publication placement for citation diversity',
      'Perplexity Pro and Enterprise visibility testing',
      'Monthly citation tracking with competitive benchmarking',
    ],
    result: 'Top clients achieve 25+ Perplexity citations per month.',
    stats: [
      { value: '25+', label: 'Citations per month (top clients)' },
      { value: '100M+', label: 'Monthly Perplexity users' },
      { value: '3x', label: 'Higher trust vs. traditional results' },
      { value: '90%', label: 'Source accuracy rate' },
    ],
    faqs: [
      { q: 'Why is Perplexity SEO particularly valuable for B2B and SaaS brands?', a: 'Perplexity caters heavily to researchers, developers, tech founders, and enterprise buyers who research software and service decisions. Perplexity always cites numbered citations, sending direct, high-intent referral traffic to sources.' },
      { q: 'What content formats perform best on Perplexity?', a: 'Original data studies, transparent comparison pages, comprehensive documentation, and objective pros-and-cons teardowns format exceptionally well for Perplexity retrieval agents.' },
      { q: 'Can we optimize existing blog posts for Perplexity indexing?', a: 'Yes. We re-engineer existing content by adding concise executive summaries, question-and-answer headers, verifiable data points, and explicit entity definitions that make citation extraction seamless.' },
    ],
  },
  {
    slug: 'seo-writing', category: 'content-marketing', parentTitle: 'Content Marketing', title: 'SEO Content Writing',
    desc: 'Long-form, answer-first content written by ex-journalists who know your industry. Every piece is built to rank, convert, and satisfy intent — not just hit a word count.',
    features: [
      'Keyword-targeted content briefs with SERP analysis',
      'Long-form articles (2,000-5,000 words) written by industry specialists',
      'Content scoring with Clearscope/Surfer for topical completeness',
      'Internal linking strategy embedded in every piece',
      'Featured snippet optimization with structured answer blocks',
      'Content refresh and update cycles for evergreen assets',
    ],
    result: 'Average 4.2x organic traffic increase from content alone.',
    stats: [
      { value: '4.2x', label: 'Avg. traffic increase from content' },
      { value: '8', label: 'Articles per month (standard retainer)' },
      { value: '92%', label: 'First-page ranking rate within 90 days' },
      { value: '0', label: 'AI-generated content. All human-written.' },
    ],
    faqs: [
      { q: 'How do your writers conduct keyword and competitor search intent research?', a: 'We analyze top-10 SERP ranking patterns, People Also Ask (PAA) questions, user forums, and customer search queries to build comprehensive topical briefs that address both informational intent and commercial conversion.' },
      { q: 'Are your SEO articles 100% original and verified for plagiarism?', a: 'Yes. Every article is written from scratch by experienced industry copywriters and rigorously checked through plagiarism and AI-detection tools before editorial delivery.' },
      { q: 'How do you ensure proper internal linking and on-page optimization?', a: 'Every brief identifies specific anchor text targets pointing to your money pages and related cluster articles, accompanied by optimized title tags, meta descriptions, header structures, and image alt text.' },
    ],
  },
  {
    slug: 'blog-management', category: 'content-marketing', parentTitle: 'Content Marketing', title: 'Blog Management',
    desc: 'A fully managed blog operation. We handle editorial calendars, writer management, publishing workflows, and performance tracking so you can focus on your business.',
    features: [
      'Monthly editorial calendar aligned with keyword strategy',
      'Writer recruitment, briefing, and quality control',
      'CMS publishing with proper on-page SEO',
      'Category and tag architecture optimization',
      'Content performance tracking and ROI reporting',
      'Quarterly content audits with prune/refresh recommendations',
    ],
    result: 'Managed blogs average 180% more organic sessions within 6 months.',
    stats: [
      { value: '180%', label: 'Avg. session increase in 6 months' },
      { value: '50+', label: 'Active blogs managed' },
      { value: '12', label: 'Avg. posts published per month' },
      { value: '96%', label: 'On-time delivery rate' },
    ],
    faqs: [
      { q: 'Who manages the editorial calendar and topic ideation?', a: 'Our content strategists build a 3-month rolling editorial roadmap based on keyword search volume, seasonal trends, and product roadmaps, presenting it for your sign-off before writer assignment.' },
      { q: 'Can you publish directly to our CMS platform?', a: 'Yes. Our team directly formats, tags, and schedules posts inside WordPress, Webflow, Contentful, Ghost, Shopify, or GitHub-based Markdown repositories.' },
      { q: 'What happens if we need revisions on a published post?', a: 'All retainers include unlimited revisions during the drafting phase and free quarterly refreshes on established articles that show signs of organic traffic decay.' },
    ],
  },
  {
    slug: 'copywriting', category: 'content-marketing', parentTitle: 'Content Marketing', title: 'Copywriting',
    desc: 'Conversion-focused copy for landing pages, product descriptions, email sequences, and ad campaigns. Written to persuade, structured to rank.',
    features: [
      'Landing page copy optimized for both SEO and conversion',
      'Product description writing at scale',
      'Email sequence copywriting (welcome, nurture, re-engagement)',
      'Ad copy for Google Ads, Meta, and LinkedIn',
      'A/B test variant creation for headlines and CTAs',
      'Brand voice development and tone guidelines',
    ],
    result: 'Average 35% conversion rate lift on landing pages we rewrite.',
    stats: [
      { value: '35%', label: 'Avg. conversion rate lift' },
      { value: '500+', label: 'Landing pages written' },
      { value: '24h', label: 'Turnaround on urgent copy' },
      { value: '4.8', label: 'Avg. client satisfaction score' },
    ],
    faqs: [
      { q: 'How do you approach landing page copywriting to balance SEO and conversions?', a: 'We employ high-converting persuasion frameworks (such as PAS and AIDA) for user engagement, while integrating high-value primary and secondary keywords naturally into H1/H2 headings and body copy without keyword stuffing.' },
      { q: 'What information do you need from our team to start copywriting?', a: 'We conduct a 45-minute intake interview to gather your ideal customer profile (ICP), value propositions, pain points, objection lists, and brand tone guidelines, along with any existing competitor teardowns.' },
      { q: 'Do you write conversion-focused A/B test variations?', a: 'Yes. We craft alternative headline variations, CTA button copy, hero benefit statements, and social proof sections for multivariate and split testing programs.' },
    ],
  },
  {
    slug: 'email-marketing', category: 'content-marketing', parentTitle: 'Content Marketing', title: 'Email Marketing',
    desc: 'Strategic email campaigns that nurture leads, retain customers, and drive repeat revenue. We handle strategy, copy, design, and performance optimization.',
    features: [
      'Email strategy aligned with customer lifecycle stages',
      'Automated sequence design (welcome, abandoned cart, post-purchase)',
      'Newsletter content creation and scheduling',
      'List segmentation and personalization strategy',
      'Deliverability optimization and domain warming',
      'A/B testing on subject lines, send times, and content',
    ],
    result: 'Average 42% open rate and 3.8% click rate across client campaigns.',
    stats: [
      { value: '42%', label: 'Avg. open rate' },
      { value: '3.8%', label: 'Avg. click-through rate' },
      { value: '28x', label: 'Avg. email ROI' },
      { value: '99.2%', label: 'Avg. deliverability rate' },
    ],
    faqs: [
      { q: 'Which email service providers (ESPs) do you support?', a: 'We work across all enterprise and growth platforms including Klaviyo, HubSpot, ActiveCampaign, Mailchimp, Customer.io, and Braze.' },
      { q: 'How do you protect domain sender reputation and email deliverability?', a: 'We configure and verify SPF, DKIM, DMARC, and BIMI DNS records, monitor spam complaint rates, execute gradual IP warming sequences, and implement automated unengaged subscriber sunset policies.' },
      { q: 'What types of automated email flows do you set up?', a: 'We engineer high-converting welcome series, abandoned cart recovery sequences, post-purchase onboarding, win-back flows, and lead nurture drips tailored to your customer journey.' },
    ],
  },
  {
    slug: 'google-ads', category: 'ppc', parentTitle: 'PPC & Paid Ads', title: 'Google Ads',
    desc: 'Performance-driven Google Ads management. Search, Shopping, Display, and Performance Max campaigns built to maximize ROAS, not just spend budget.',
    features: [
      'Campaign architecture and account restructuring',
      'Keyword research with negative keyword mining',
      'Ad copy creation with A/B testing frameworks',
      'Landing page alignment and quality score optimization',
      'Bid strategy optimization (tCPA, tROAS, maximize conversions)',
      'Conversion tracking setup and attribution modeling',
      'Shopping feed optimization for e-commerce',
      'Monthly performance reporting with actionable insights',
    ],
    result: 'Average 3.2x ROAS improvement within first 90 days.',
    stats: [
      { value: '3.2x', label: 'Avg. ROAS improvement' },
      { value: '$2M+', label: 'Monthly ad spend managed' },
      { value: '90', label: 'Days to measurable ROAS lift' },
      { value: '94%', label: 'Client retention' },
    ],
    faqs: [
      { q: 'How do you structure Google Ads campaigns for optimal budget efficiency?', a: 'We isolate campaigns by search intent—separating high-intent exact match keywords, branded terms, and broad-match exploratory ad groups with strict negative keyword lists to prevent budget bleed.' },
      { q: 'Do you manage Performance Max (PMax) campaigns?', a: 'Yes. We build structured PMax campaigns with high-quality audience signals, custom asset groups, and brand exclusion lists, preventing PMax from cannibalizing organic brand search.' },
      { q: 'How do you track conversions accurately with privacy changes?', a: 'We implement Google Tag Manager with enhanced conversions, server-side tagging, and Consent Mode v2 to ensure maximum tracking fidelity while staying fully compliant.' },
    ],
  },
  {
    slug: 'meta-ads', category: 'ppc', parentTitle: 'PPC & Paid Ads', title: 'Meta Ads',
    desc: 'Facebook and Instagram advertising that drives real business results. Full-funnel campaign management from awareness to conversion with creative strategy included.',
    features: [
      'Audience building using interest, behavior, and lookalike targeting',
      'Creative strategy and ad format recommendations',
      'Campaign structure optimization for the algorithm',
      'Retargeting sequences across the customer journey',
      'Conversion API setup for iOS 14+ tracking accuracy',
      'Budget allocation and scaling strategy',
    ],
    result: 'Average 2.8x ROAS across e-commerce clients.',
    stats: [{ value: '2.8x', label: 'Avg. ROAS' }, { value: '45%', label: 'Lower CPA vs. industry avg' }, { value: '200+', label: 'Campaigns managed' }, { value: '87%', label: 'Creative test win rate' }],
    faqs: [
      { q: 'How do you navigate iOS 14+ tracking limitations on Meta Ads?', a: 'We deploy Meta Conversions API (CAPI) through server-side GTM, deduplicating browser and server events to ensure complete attribution and reliable algorithmic optimization.' },
      { q: 'What is your creative testing methodology on Facebook and Instagram?', a: 'We run iterative dynamic creative testing (DCT) sprints, isolating hooks, visual styles (UGC vs polished graphic vs founder video), and calls-to-action before scaling winning assets with increased budget.' },
      { q: 'What budget is recommended to begin Meta Ads campaigns?', a: 'We recommend a minimum media budget of $3,000 to $5,000 per month to allow Meta machine learning algorithms to complete the initial learning phase and achieve statistical significance.' },
    ],
  },
  {
    slug: 'youtube-ads', category: 'ppc', parentTitle: 'PPC & Paid Ads', title: 'YouTube Ads',
    desc: 'Video advertising on the world\'s second-largest search engine. We create campaigns that drive awareness, consideration, and action with precise targeting.',
    features: [
      'Campaign strategy across TrueView, Bumper, and In-Feed formats',
      'Audience targeting using intent signals and custom segments',
      'Video creative consultation and script guidance',
      'Landing page optimization for video traffic',
      'Brand lift and conversion measurement setup',
      'Remarketing sequences for video viewers',
    ],
    result: 'Average 65% lower cost-per-view vs. industry benchmarks.',
    stats: [{ value: '65%', label: 'Lower CPV vs. benchmarks' }, { value: '4.2%', label: 'Avg. view-through rate' }, { value: '120+', label: 'Video campaigns managed' }, { value: '2.1x', label: 'Avg. brand lift' }],
    faqs: [
      { q: 'What video formats work best for YouTube advertising campaigns?', a: 'We focus on Skippable In-Stream ads using the ABCD creative framework (Attract, Brand, Connect, Direct) with strong 5-second hooks, complemented by non-skippable bumper ads for frequency capping.' },
      { q: 'Do you assist with YouTube video creative and scripting?', a: 'Yes. We craft high-converting video storyboard scripts, advise on visual pacing, and can edit raw customer footage or studio video into performance ad variants.' },
      { q: 'How do you measure business lift from YouTube view-through conversions?', a: 'We configure Google Ads view-through attribution windows, brand search lift studies, and post-purchase attribution surveys to evaluate direct and indirect revenue contribution.' },
    ],
  },
  {
    slug: 'programmatic', category: 'ppc', parentTitle: 'PPC & Paid Ads', title: 'Programmatic Advertising',
    desc: 'Automated media buying across display, video, native, and connected TV. We use data-driven targeting to reach your audience wherever they browse.',
    features: [
      'DSP setup and management (DV360, The Trade Desk)',
      'Audience segmentation using first and third-party data',
      'Cross-channel campaign orchestration',
      'Brand safety and viewability controls',
      'Attribution modeling and incrementality testing',
      'Real-time optimization and bid management',
    ],
    result: 'Average 40% improvement in media efficiency vs. direct buys.',
    stats: [{ value: '40%', label: 'Avg. media efficiency gain' }, { value: '95%', label: 'Viewability rate' }, { value: '0.08%', label: 'Avg. invalid traffic rate' }, { value: '3.5x', label: 'Reach efficiency vs. direct' }],
    faqs: [
      { q: 'What demand-side platforms (DSPs) do you utilize?', a: 'We leverage Google Display & Video 360 (DV360) and The Trade Desk for enterprise media buys, alongside specialized CTV and native ad networks.' },
      { q: 'How do you prevent ad fraud and non-human bot traffic in programmatic campaigns?', a: 'We enforce pre-bid fraud filters through IAS (Integral Ad Science) or DoubleVerify, maintain private marketplace (PMP) deal IDs with premium publishers, and exclude low-quality app inventories.' },
      { q: 'What is the difference between programmatic display and Google Display Network?', a: 'While GDN is limited to Google partner sites, programmatic DSPs give access to 95%+ of global web inventory, Connected TV (Hulu, Roku), digital audio (Spotify), and advanced first-party data onboarding.' },
    ],
  },
  {
    slug: 'management', category: 'social-media', parentTitle: 'Social Media', title: 'Social Media Management',
    desc: 'Full-service social media management. We handle content creation, scheduling, community engagement, and performance reporting across all major platforms.',
    features: [
      'Content calendar creation and scheduling',
      'Original content creation (graphics, video, copy)',
      'Community management and response handling',
      'Platform-specific optimization (Instagram, LinkedIn, TikTok, X)',
      'Hashtag strategy and trend monitoring',
      'Monthly analytics and performance reporting',
    ],
    result: 'Average 156% follower growth and 3.2x engagement increase in 6 months.',
    stats: [{ value: '156%', label: 'Avg. follower growth' }, { value: '3.2x', label: 'Engagement increase' }, { value: '40+', label: 'Brands managed' }, { value: '98%', label: 'On-time content delivery' }],
    faqs: [
      { q: 'How many posts per week are included in social management packages?', a: 'Depending on your retainer tier, we publish between 3 to 7 tailored posts per week per platform, combining carousels, short-form reels, industry thought leadership, and text discussions.' },
      { q: 'Do we need to supply all photos and video assets?', a: 'Not necessarily. While authentic behind-the-scenes footage from your team is highly encouraged, our creative team designs custom graphics, motion animations, typography carousels, and curated visual assets.' },
      { q: 'How do you handle crisis communication or negative social comments?', a: 'We develop an approved escalation playbook during onboarding. Minor issues receive brand-aligned polite de-escalation, while high-severity matters are escalated to your internal leadership within 30 minutes.' },
    ],
  },
  {
    slug: 'advertising', category: 'social-media', parentTitle: 'Social Media', title: 'Social Advertising',
    desc: 'Paid social campaigns that drive measurable business outcomes. We manage ad spend across Meta, LinkedIn, TikTok, and X with a focus on ROAS.',
    features: [
      'Campaign strategy and audience research',
      'Ad creative development and testing',
      'Budget optimization across platforms',
      'Retargeting and lookalike audience building',
      'Conversion tracking and attribution setup',
      'Weekly performance optimization and reporting',
    ],
    result: 'Average 2.4x ROAS across all social platforms.',
    stats: [{ value: '2.4x', label: 'Avg. ROAS' }, { value: '35%', label: 'Lower CPL vs. benchmarks' }, { value: '500+', label: 'Ad creatives tested' }, { value: '89%', label: 'Client retention' }],
    faqs: [
      { q: 'Which social channels deliver the lowest cost per customer acquisition?', a: 'This varies by sector: LinkedIn delivers the highest-quality qualified leads for high-ticket B2B services, while Meta and TikTok dominate direct-to-consumer e-commerce acquisition costs.' },
      { q: 'How do you scale ad spend without driving up customer acquisition costs?', a: 'We employ horizontal scaling (expanding into new lookalike and interest audiences) and creative diversification, preventing ad fatigue and maintaining stable CPAs as spend rises.' },
      { q: 'What reporting frequency can we expect for paid social campaigns?', a: 'You receive weekly automated performance dashboards and bi-weekly strategic calls with your dedicated paid media director to review spend, ROAS, and creative testing results.' },
    ],
  },
  {
    slug: 'brand', category: 'social-media', parentTitle: 'Social Media', title: 'Brand Management',
    desc: 'Strategic brand positioning and reputation management across digital channels. We build and protect the brand identity that makes your business memorable.',
    features: [
      'Brand voice and tone development',
      'Visual identity guidelines for digital channels',
      'Reputation monitoring and crisis response protocols',
      'Competitor brand analysis and positioning strategy',
      'Brand sentiment tracking and reporting',
      'Influencer partnership strategy and management',
    ],
    result: 'Average 78% improvement in brand sentiment scores.',
    stats: [{ value: '78%', label: 'Brand sentiment improvement' }, { value: '24/7', label: 'Reputation monitoring' }, { value: '60+', label: 'Brands managed' }, { value: '4.9', label: 'Client satisfaction score' }],
    faqs: [
      { q: 'What deliverables are included in digital brand management?', a: 'We provide comprehensive visual identity guidelines, digital tone of voice manuals, social media asset design kits, executive personal branding templates, and online reputation management.' },
      { q: 'How do you monitor brand reputation across the web and social media?', a: 'We utilize enterprise listening tools (Brandwatch, Mention) to monitor brand keywords, competitor mentions, executive names, and sentiment trends in real time across forums, social media, and news outlets.' },
      { q: 'Can you help rehabilitate a damaged brand reputation or outdated image?', a: 'Yes. We develop multi-phase brand revitalization campaigns: auditing public perception, revamping visual assets, deploying positive digital PR, and suppressing negative search results with high-authority branded properties.' },
    ],
  },
  {
    slug: 'custom', category: 'web-design', parentTitle: 'Web Design', title: 'Custom Web Design',
    desc: 'Bespoke website design built for performance, conversion, and SEO from the ground up. No templates, no themes — every pixel is purposeful.',
    features: [
      'Discovery workshop and brand strategy alignment',
      'Custom UI/UX design with Figma prototyping',
      'Mobile-first responsive development',
      'SEO-optimized architecture and page speed',
      'CMS integration (WordPress, Webflow, or headless)',
      'Launch support and post-launch optimization',
    ],
    result: 'Average 52% conversion rate improvement on redesigned sites.',
    stats: [{ value: '52%', label: 'Avg. conversion lift' }, { value: '200+', label: 'Sites designed' }, { value: '< 2s', label: 'Avg. page load time' }, { value: '100', label: 'Lighthouse performance score target' }],
    faqs: [
      { q: 'Do you use pre-made templates or build custom websites from scratch?', a: 'Every website we build is 100% custom-designed in Figma based on your specific brand identity, conversion objectives, and user experience requirements. We never use generic pre-bought templates.' },
      { q: 'How do you ensure our custom website is fast and mobile-responsive?', a: 'We design mobile-first across all modern device breakpoints (mobile, tablet, desktop, ultrawide). Our front-end engineering adheres to strict Core Web Vitals performance benchmarks (<1.2s LCP).' },
      { q: 'What deliverables do we receive at the conclusion of the web design phase?', a: 'You receive fully organized Figma source files, interactive clickable prototypes, an atomic design system with typography and color tokens, exported SVGs, and complete developer handoff documentation.' },
    ],
  },
  {
    slug: 'wordpress', category: 'web-design', parentTitle: 'Web Design', title: 'WordPress Design',
    desc: 'Custom WordPress development optimized for speed, security, and SEO. We build sites that your team can actually manage without calling a developer.',
    features: [
      'Custom theme development (no page builders)',
      'Advanced Custom Fields (ACF) for flexible content',
      'WooCommerce integration for e-commerce',
      'Security hardening and maintenance plans',
      'Plugin audit and performance optimization',
      'Content migration and launch support',
    ],
    result: 'Average 3x speed improvement vs. template-based WordPress sites.',
    stats: [{ value: '3x', label: 'Speed improvement vs. templates' }, { value: '150+', label: 'WordPress sites built' }, { value: '99.9%', label: 'Uptime guarantee' }, { value: 'A+', label: 'Security rating' }],
    faqs: [
      { q: 'Why do you build custom WordPress themes instead of using Elementor or Divi?', a: 'Heavy page builders bloat code, inject hundreds of external CSS/JS scripts, and severely damage Google PageSpeed scores. Our lightweight custom Gutenberg or ACF themes load in under 1 second and offer a frictionless editing experience.' },
      { q: 'Can non-technical team members easily update content and add blog posts?', a: 'Yes. We configure custom fields and tailored block patterns so your marketing team can easily change copy, swap images, and create new landing pages without writing code or breaking layouts.' },
      { q: 'How do you keep WordPress websites secure from malware and vulnerabilities?', a: 'We implement enterprise security headers, two-factor authentication, Cloudflare WAF protection, automated daily off-site backups, and strict plugin curation to prevent vulnerabilities.' },
    ],
  },
  {
    slug: 'ecommerce', category: 'web-design', parentTitle: 'Web Design', title: 'E-commerce Design',
    desc: 'Online store design that converts browsers into buyers. We build shopping experiences optimized for mobile, speed, and average order value.',
    features: [
      'Conversion-optimized product page templates',
      'Cart and checkout flow optimization',
      'Product photography guidelines and integration',
      'Payment gateway and shipping configuration',
      'Inventory management system integration',
      'Post-launch CRO testing and optimization',
    ],
    result: 'Average 45% increase in online revenue within 90 days of launch.',
    stats: [{ value: '45%', label: 'Avg. revenue increase' }, { value: '100+', label: 'Stores launched' }, { value: '3.2%', label: 'Avg. conversion rate achieved' }, { value: '< 1.5s', label: 'Avg. mobile load time' }],
    faqs: [
      { q: 'Which e-commerce platforms do you specialize in designing for?', a: 'We specialize in custom Shopify, Shopify Plus, WooCommerce, and headless commerce architectures (Next.js commerce connected to Shopify or Medusa backends).' },
      { q: 'How do you optimize product pages for maximum average order value (AOV)?', a: 'We incorporate strategic cross-sell and upsell modules, volume discount tiers, sticky add-to-cart buttons, trust badges, customer reviews, and rapid express checkout flows (Shop Pay, Apple Pay).' },
      { q: 'Can you integrate our custom inventory, ERP, or shipping software?', a: 'Yes. Our developers integrate third-party logistics (3PL), ERP systems, CRM platforms (HubSpot, Salesforce), and custom payment gateways through secure REST or GraphQL APIs.' },
    ],
  },
  {
    slug: 'redesign', category: 'web-design', parentTitle: 'Web Design', title: 'Website Redesign',
    desc: 'Strategic website redesigns that improve performance without losing SEO equity. We migrate, restructure, and rebuild with zero ranking loss as a non-negotiable.',
    features: [
      'Pre-redesign SEO audit and URL mapping',
      'Information architecture restructuring',
      'Content audit with migrate/update/retire decisions',
      '301 redirect strategy and implementation',
      'Post-launch monitoring and recovery plan',
      'Performance benchmarking before and after',
    ],
    result: '100% of redesign clients maintained or improved organic traffic.',
    stats: [{ value: '0%', label: 'Traffic loss on redesigns' }, { value: '80+', label: 'Redesigns completed' }, { value: '28%', label: 'Avg. traffic increase post-redesign' }, { value: '100%', label: 'Redirect coverage' }],
    faqs: [
      { q: 'How do you guarantee we will not lose our Google organic search rankings during a redesign?', a: 'We conduct a comprehensive pre-launch URL inventory, map 100% of old URLs to new counterparts with permanent 301 redirects, preserve existing on-page header and metadata structures, and test redirect chains in staging before DNS cutover.' },
      { q: 'How long does a full website redesign typically take?', a: 'A standard marketing website redesign requires 6 to 10 weeks from discovery to launch, split into discovery, wireframing, high-fidelity UI design, development, content migration, QA testing, and launch.' },
      { q: 'Can we retain our existing blog posts and customer data during the redesign?', a: 'Yes. We execute automated database migrations for all legacy articles, customer accounts, and order histories, ensuring complete data continuity.' },
    ],
  },
  {
    slug: 'digital-pr', category: 'link-building', parentTitle: 'Link Building', title: 'Digital PR',
    desc: 'Earn editorial backlinks from publications your customers actually read. Data-driven PR campaigns that generate coverage, links, and brand awareness simultaneously.',
    features: [
      'Data-driven PR campaign ideation and execution',
      'Original research and survey-based content creation',
      'Journalist relationship building and pitch outreach',
      'Press release writing and distribution',
      'Publication targeting based on domain authority and relevance',
      'Coverage tracking and link acquisition reporting',
    ],
    result: 'Average 15 editorial placements per campaign.',
    stats: [{ value: '15', label: 'Avg. placements per campaign' }, { value: 'DR 60+', label: 'Avg. linking domain rating' }, { value: '200+', label: 'Media relationships' }, { value: '92%', label: 'Campaign success rate' }],
    faqs: [
      { q: 'What types of stories and campaigns do you create for digital PR?', a: 'We build proprietary industry survey reports, data journalism studies, interactive calculators, and expert commentary pitches that provide genuine newsworthy value to journalists and editors.' },
      { q: 'What publications have your digital PR campaigns been featured in?', a: 'Our campaigns have earned editorial coverage in top-tier publications including Forbes, TechCrunch, Business Insider, Fast Company, Inc., and major national news outlets.' },
      { q: 'Are digital PR links guaranteed to be dofollow?', a: 'While editorial discretion rests with the publishing journalist, over 85% of our earned placements feature contextual dofollow links that directly pass topical authority and PageRank.' },
    ],
  },
  {
    slug: 'guest-posting', category: 'link-building', parentTitle: 'Link Building', title: 'Guest Posting',
    desc: 'Strategic guest content placement on authoritative sites in your industry. Every placement is editorial, relevant, and built for long-term value.',
    features: [
      'Publication prospecting based on relevance and authority',
      'Topic ideation aligned with your keyword strategy',
      'Full article writing by subject matter experts',
      'Editorial relationship management',
      'Anchor text strategy and internal linking from guest posts',
      'Monthly placement reporting with link metrics',
    ],
    result: 'Average DR 55+ for guest post placements.',
    stats: [{ value: 'DR 55+', label: 'Avg. placement quality' }, { value: '8-12', label: 'Placements per month' }, { value: '100%', label: 'Editorial placements (no PBNs)' }, { value: '0', label: 'Link penalties. Ever.' }],
    faqs: [
      { q: 'How do you ensure guest post sites are authoritative and not link farms?', a: 'We manually review every domain: checking for steady organic Google traffic trends, strict editorial guidelines, real author bios, and diverse inbound link profiles. We strictly ban PBNs and public blog directories.' },
      { q: 'Who writes the guest post articles?', a: 'Our in-house editorial team of subject-matter writers crafts in-depth, educational articles (1,200–2,000 words) tailored to the specific publishing website audience guidelines.' },
      { q: 'Can we choose the anchor text for our backlinks?', a: 'Yes. We plan a balanced anchor text mix (branded, topical partial-match, and natural URL anchors) to ensure search engine safety and maximize contextual relevance.' },
    ],
  },
  {
    slug: 'outreach', category: 'link-building', parentTitle: 'Link Building', title: 'Outreach Campaigns',
    desc: 'Targeted outreach to earn links from relevant sites through broken link building, resource page placement, unlinked mention reclamation, and strategic partnerships.',
    features: [
      'Broken link building at scale',
      'Unlinked brand mention reclamation',
      'Resource page and listicle placement',
      'Competitor backlink gap analysis and replication',
      'Partnership and co-marketing link opportunities',
      'Toxic link audit and disavow management',
    ],
    result: 'Average 20 new referring domains per month.',
    stats: [{ value: '20', label: 'New referring domains per month' }, { value: '35%', label: 'Response rate on outreach' }, { value: '500+', label: 'Outreach campaigns run' }, { value: '0', label: 'Spam links. Ever.' }],
    faqs: [
      { q: 'What outreach strategies do you use beyond standard cold pitching?', a: 'We utilize broken link building, resource page curation pitches, unlinked brand mention reclamation, and skyscraper content upgrades that provide genuine value to webmasters.' },
      { q: 'How do you personalize outreach emails to get high response rates?', a: 'Every pitch is sent from a real team member who researches the author recent articles and specific site needs. We never blast automated unpersonalized spam templates.' },
      { q: 'What reporting do you provide during an outreach campaign?', a: 'You receive live access to our outreach tracker showing contacted prospects, response rates, negotiated placements, and live verified links with domain authority metrics.' },
    ],
  },
  {
    slug: 'cro-audits', category: 'analytics', parentTitle: 'Analytics & CRO', title: 'CRO Audits',
    desc: 'Systematic conversion rate optimization audits that identify exactly why visitors aren\'t converting and what to fix first. Data-driven, not opinion-driven.',
    features: [
      'Heatmap and session recording analysis',
      'Funnel analysis with drop-off identification',
      'Form analytics and abandonment analysis',
      'User survey and feedback integration',
      'Competitor UX benchmarking',
      'Prioritized recommendation report with expected impact',
    ],
    result: 'Average 28% conversion rate improvement from audit recommendations.',
    stats: [{ value: '28%', label: 'Avg. conversion lift' }, { value: '150+', label: 'CRO audits delivered' }, { value: '72h', label: 'Turnaround on urgent audits' }, { value: '3.2x', label: 'Avg. ROI from recommendations' }],
    faqs: [
      { q: 'What tools and methodologies do you use during a CRO audit?', a: 'We combine quantitative analytics (GA4 conversion funnels, heatmaps, scroll maps) with qualitative behavioral insights (session recordings, user feedback polls, and heuristic usability evaluations).' },
      { q: 'How do you prioritize conversion recommendations?', a: 'We score every finding using the ICE framework (Impact, Confidence, Ease), ensuring your team tackles low-hanging fruit with high revenue upside first.' },
      { q: 'What kind of conversion lift can we expect from audit fixes?', a: 'Clients typically experience an immediate 15% to 35% conversion lift after implementing our top-tier UX, checkout, and landing page recommendations.' },
    ],
  },
  {
    slug: 'ab-testing', category: 'analytics', parentTitle: 'Analytics & CRO', title: 'A/B Testing',
    desc: 'Rigorous experimentation programs that validate changes before you commit. We design, build, and analyze tests that move revenue metrics, not vanity metrics.',
    features: [
      'Hypothesis development based on data analysis',
      'Test design with statistical significance planning',
      'Variant creation (copy, layout, UX, pricing)',
      'Test implementation using VWO, Optimizely, or Google Optimize',
      'Statistical analysis and result interpretation',
      'Winner implementation and documentation',
    ],
    result: 'Average 85% test validity rate with clear winners.',
    stats: [{ value: '85%', label: 'Test validity rate' }, { value: '500+', label: 'Tests run' }, { value: '22%', label: 'Avg. lift from winning tests' }, { value: '95%', label: 'Statistical confidence threshold' }],
    faqs: [
      { q: 'How do you know when an A/B test has reached statistical significance?', a: 'We maintain a strict 95% statistical confidence threshold with adequate sample size and full business cycle duration (minimum 2–4 weeks) to rule out false positives or seasonality anomalies.' },
      { q: 'Which experimentation platforms do you support?', a: 'We implement and manage tests in VWO, Optimizely, Kameleoon, AB Tasty, and custom server-side testing frameworks.' },
      { q: 'What happens when a test variation loses?', a: 'Losing tests provide invaluable customer behavior insights. We document the learnings, refine our customer hypothesis, and iterate on new variations without risking core business revenue.' },
    ],
  },
  {
    slug: 'dashboards', category: 'analytics', parentTitle: 'Analytics & CRO', title: 'Reporting Dashboards',
    desc: 'Live, always-on dashboards that connect your marketing data to business outcomes. Built in Looker Studio with revenue attribution, not just traffic metrics.',
    features: [
      'Custom Looker Studio dashboard design and build',
      'Multi-source data integration (GA4, GSC, CRM, ads)',
      'Revenue attribution modeling',
      'Automated alerting for traffic drops and anomalies',
      'Executive summary views for leadership',
      'Monthly report generation with strategist commentary',
    ],
    result: 'Average 60% reduction in reporting time for marketing teams.',
    stats: [{ value: '60%', label: 'Reduction in reporting time' }, { value: '100+', label: 'Dashboards built' }, { value: 'Real-time', label: 'Data refresh frequency' }, { value: '4.9', label: 'Client satisfaction score' }],
    faqs: [
      { q: 'Which data sources can you connect into our reporting dashboard?', a: 'We integrate Google Analytics 4, Google Search Console, Google Ads, Meta Ads, LinkedIn Ads, Shopify, Stripe, HubSpot, Salesforce, and custom SQL databases.' },
      { q: 'How often does dashboard data refresh?', a: 'Dashboards refresh automatically in real-time or every 15 to 60 minutes depending on API limits, providing continuous 24/7 visibility into key performance indicators.' },
      { q: 'Can we share executive-level summaries with our leadership or board?', a: 'Yes. We build high-level executive summary views with clean visual charts and automated monthly PDF report delivery scheduled directly to your stakeholders.' },
    ],
  },
]

export function getSubService(category: string, slug: string): SubService | undefined {
  return allSubServices.find(s => s.category === category && s.slug === slug)
}

export function getSubServiceSlugs(): [string, string][] {
  return allSubServices.map(s => [s.category, s.slug])
}

export function getSubServicesByCategory(category: string): SubService[] {
  return allSubServices.filter(s => s.category === category)
}
